# Revision

In [1]:
def quick_sort(arr):
    if(len(arr)<=1):
        return arr
    pivot=arr[0]
    left=[x for x in arr if x<pivot]
    middle=[x for x in arr if x==pivot]
    right=[x for x in arr if x>pivot]
    return quick_sort(left)+middle+quick_sort(right)

In [2]:
quick_sort([7,6,10,5,9,2,1,15,7])

[1, 2, 5, 6, 7, 7, 9, 10, 15]

In [3]:
x=3
print(x,type(x))

3 <class 'int'>


In [4]:
print("{},{},{}".format(1,2,3))

1,2,3


In [5]:
print('{} {} {}'.format('shalu',86,95))

shalu 86 95


In [6]:
print('     world    '.strip()+" shalu")

world shalu


In [7]:
nums=[0,1,2,3,4]
d={x:x**2 for x in nums}

In [8]:
d

{0: 0, 1: 1, 2: 4, 3: 9, 4: 16}

In [9]:
s={1,2,3}

In [10]:
s

{1, 2, 3}

In [11]:
s.add(4)

In [12]:
s

{1, 2, 3, 4}

In [13]:
s.add('shalu')

In [14]:
s

{1, 2, 3, 4, 'shalu'}

In [15]:
import numpy as np

In [16]:
l=np.array([[1,2,3],[4,5,6]])

In [17]:
l

array([[1, 2, 3],
       [4, 5, 6]])

In [18]:
l.shape

(2, 3)

In [19]:
c=np.full((2,2),7)

In [20]:
c

array([[7, 7],
       [7, 7]])

In [21]:
c=np.full((3,2),5)

In [22]:
c

array([[5, 5],
       [5, 5],
       [5, 5]])

In [23]:
import numpy as np

In [24]:
l=np.array([1,2,3])

In [25]:
l

array([1, 2, 3])

In [26]:
l.shape

(3,)

In [27]:
my=np.array([[1,2,3],[4,5,6],[7,8,9]])

In [28]:
my

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [29]:
my.shape

(3, 3)

In [30]:
l=np.arange(1,10)

In [31]:
l

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [32]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [33]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [34]:
np.ones((1))

array([1.])

In [35]:
np.ones((1,1))

array([[1.]])

In [36]:
np.ones((1,3))

array([[1., 1., 1.]])

In [37]:
np.linspace(0,10,2)

array([ 0., 10.])

In [38]:
np.linspace(1,9,20)

array([1.        , 1.42105263, 1.84210526, 2.26315789, 2.68421053,
       3.10526316, 3.52631579, 3.94736842, 4.36842105, 4.78947368,
       5.21052632, 5.63157895, 6.05263158, 6.47368421, 6.89473684,
       7.31578947, 7.73684211, 8.15789474, 8.57894737, 9.        ])

In [39]:
np.eye(3,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [40]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [41]:
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [42]:
np.random.random(3)

array([0.6533078 , 0.33866732, 0.68852365])

In [43]:
np.random.rand(3)

array([0.10246627, 0.82180075, 0.3241482 ])

In [44]:
np.random.rand(3,4)

array([[0.20890643, 0.975237  , 0.80667548, 0.72039088],
       [0.6036339 , 0.39974693, 0.0611937 , 0.52718434],
       [0.01043084, 0.41449401, 0.13059552, 0.87842907]])

In [45]:
np.random.randn(3,4)

array([[ 0.25074745, -0.42678148, -0.93427999, -0.25110804],
       [ 1.69089481, -0.5899388 , -0.64331091,  0.20200753],
       [-0.54060895,  0.48169012,  1.42320441,  0.95941038]])

In [46]:
np.random.randint(1,100)

66

In [47]:
np.random.randint(10)

5

In [48]:
np.random.randint(1,100,10)

array([ 3, 86, 82, 35,  2,  9, 80, 17, 94, 94])

In [49]:
np.arange(25).reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [50]:
arr=np.arange(1,26).reshape(5,5)

In [51]:
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [52]:
arr.max()

25

In [53]:
arr.min()

1

In [54]:
arr.shape

(5, 5)

In [55]:
arr.argmax()

24

In [56]:
arr=np.array([[1,2],[3,4],[5,6]])

In [57]:
arr

array([[1, 2],
       [3, 4],
       [5, 6]])

In [58]:
p=arr>2

In [59]:
p

array([[False, False],
       [ True,  True],
       [ True,  True]])

In [60]:
arr[arr>2]

array([3, 4, 5, 6])

In [61]:
x=np.array([[1,2],[3,4]])
y=np.array([[5,6],[7,8]])

In [62]:
print(x)
print(y)

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]


In [63]:
print(x+y)

[[ 6  8]
 [10 12]]


In [64]:
print(np.add(x,y))

[[ 6  8]
 [10 12]]


In [65]:
v=np.array([9,10])
w=np.array([11,12])

In [66]:
print(v)
print(w)

[ 9 10]
[11 12]


In [67]:
print(v.dot(w))

219


In [68]:
print(np.dot(v,w))

219


In [69]:
print(v@w)

219


In [70]:
print(x.dot(w))

[35 81]


In [71]:
x=np.array([[1,2],[3,4]])

In [72]:
np.sum(x)

10

In [73]:
np.sum(x,axis=0)

array([4, 6])

In [74]:
np.sum(x,axis=1)

array([3, 7])

In [75]:
x.T

array([[1, 3],
       [2, 4]])

In [76]:
np.transpose(x)

array([[1, 3],
       [2, 4]])

In [77]:
x=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
v=np.array([1,0,1])
y=np.empty_like(x)

In [78]:
for i in range(4):
    y[i,:]=x[i,:]+v

In [79]:
print(y)

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


In [80]:
y[3,:]

array([11, 11, 13])

In [81]:
vv=np.tile(v,(4,2))

In [82]:
vv

array([[1, 0, 1, 1, 0, 1],
       [1, 0, 1, 1, 0, 1],
       [1, 0, 1, 1, 0, 1],
       [1, 0, 1, 1, 0, 1]])