In [1]:
import pandas as pd
import numpy as np 
import matplotlib.pyplot as plt
import sklearn
from sklearn.neural_network import MLPClassifier
from sklearn.neural_network import MLPRegressor

# Import necessary modules
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error
from math import sqrt
from sklearn.metrics import r2_score

In [2]:
df = pd.read_csv('diabetes.csv') 
df.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0  
2                     0.672   32        1  
3                     0.167   21        0  
4                     2.288   33        1

In [5]:
target_column = ['Age']
predictors = list(set(list(df.columns))-set(target_column))
df[predictors] = df[predictors]/df[predictors].max()
target_column

['Age']

In [6]:
X = df[predictors].values
y = df[target_column].values
X.shape
y

array([[50],
       [31],
       [32],
       [21],
       [33],
       [30],
       [26],
       [29],
       [53],
       [54],
       [30],
       [34],
       [57],
       [59],
       [51],
       [32],
       [31],
       [31],
       [33],
       [32],
       [27],
       [50],
       [41],
       [29],
       [51],
       [41],
       [43],
       [22],
       [57],
       [38],
       [60],
       [28],
       [22],
       [28],
       [45],
       [33],
       [35],
       [46],
       [27],
       [56],
       [26],
       [37],
       [48],
       [54],
       [40],
       [25],
       [29],
       [22],
       [31],
       [24],
       [22],
       [26],
       [30],
       [58],
       [42],
       [21],
       [41],
       [31],
       [44],
       [22],
       [21],
       [39],
       [36],
       [24],
       [42],
       [32],
       [38],
       [54],
       [25],
       [27],
       [28],
       [26],
       [42],
       [23],
       [22],
       [22],
       [41],

In [7]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.30, random_state=40)
print(X_train.shape); print(X_test.shape)

(537, 8)
(231, 8)


In [8]:
from sklearn.neural_network import MLPClassifier
mlp = MLPClassifier(hidden_layer_sizes=(8,8,8), activation='relu', solver='adam', max_iter=500)
mlp.fit(X_train,y_train)
predict_train = mlp.predict(X_train)
predict_test = mlp.predict(X_test)

C:\Users\gaurav\anaconda3\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:934: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\gaurav\anaconda3\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:571: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)


In [9]:
from sklearn.metrics import classification_report,confusion_matrix
print(confusion_matrix(y_train,predict_train))
print(classification_report(y_train,predict_train))

[[26 18  0 ...  0  0  0]
 [27 13  0 ...  0  0  0]
 [12  8  0 ...  0  0  0]
 ...
 [ 0  0  0 ...  0  0  0]
 [ 0  0  0 ...  0  0  0]
 [ 1  0  0 ...  0  0  0]]
              precision    recall  f1-score   support

          21       0.23      0.54      0.33        48
          22       0.10      0.27      0.15        48
          23       0.00      0.00      0.00        28
          24       0.20      0.05      0.08        39
          25       0.11      0.16      0.13        31
          26       0.00      0.00      0.00        27
          27       0.00      0.00      0.00        20
          28       0.00      0.00      0.00        23
          29       0.04      0.12      0.06        24
          30       0.00      0.00      0.00        13
          31       0.00      0.00      0.00        17
          32       0.00      0.00      0.00         9
          33       0.10      0.07      0.08        15
          34       0.00      0.00      0.00        11
          35       0.00      0.00

C:\Users\gaurav\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1272: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [10]:
print(confusion_matrix(y_test,predict_test))
print(classification_report(y_test,predict_test))

[[ 9  4  0 ...  0  0  0]
 [10 10  0 ...  0  0  0]
 [ 4  4  0 ...  0  0  0]
 ...
 [ 1  0  0 ...  0  0  0]
 [ 0  0  0 ...  0  0  0]
 [ 0  0  0 ...  0  0  0]]
              precision    recall  f1-score   support

          21       0.21      0.60      0.31        15
          22       0.20      0.42      0.27        24
          23       0.00      0.00      0.00        10
          24       0.25      0.29      0.27         7
          25       0.06      0.06      0.06        17
          26       0.00      0.00      0.00         6
          27       0.00      0.00      0.00        12
          28       0.00      0.00      0.00        12
          29       0.06      0.40      0.10         5
          30       0.00      0.00      0.00         8
          31       0.00      0.00      0.00         7
          32       0.00      0.00      0.00         7
          33       0.00      0.00      0.00         2
          34       0.00      0.00      0.00         3
          35       0.00      0.00